In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
print(tf.__version__)

2.12.0


In [ ]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import cifar10

In [ ]:
input_shape = (1, 4, 4, 2)
x = tf.constant( [[
                    [[1.0, 2],
                     [1, 1],
                     [2, 1],
                     [1, 1]],

                    [[1, 1],
                     [3, 1],
                     [1, 2],
                     [1, 1]],

                    [[1, 1],
                     [1, 2],
                     [3, 1],
                     [1, 1]],

                    [[3, 1],
                     [1, 1],
                     [1, 1],
                     [2, 1]]
                 ]])


conv_layer = tf.keras.layers.Conv2D(filters=3, kernel_size=(3, 3), activation='relu', strides=(1, 1), padding='valid')
conv_layer.build(input_shape)
weights_data = [
    tf.constant( [[[[ 0.17961133,  0.22007972, -0.2598019 ],
                    [ 0.3186909 ,  0.24281353,  0.32523507]],

                    [[ 0.11649853, -0.19694139, -0.3283413 ],
                    [-0.10513568,  0.23352385,  0.13405755]],

                    [[-0.12504146, -0.14563793,  0.35750693],
                    [ 0.0198659 , -0.12209228,  0.17227197]]],


                  [[[ 0.24108452, -0.3303193 ,  0.10114965],
                    [-0.11957595, -0.3395833 , -0.03018716]],

                    [[-0.20335948,  0.26378292, -0.2866226 ],
                    [ 0.19164538,  0.32580817,  0.03058186]],

                    [[ 0.36354887, -0.1988679 , -0.34951177],
                    [-0.11006111,  0.19815278, -0.03410023]]],


                  [[[ 0.30214107,  0.2538708 , -0.24634236],
                    [ 0.33849055,  0.04826209, -0.04467008]],

                    [[-0.03986514,  0.21542007, -0.15578839],
                    [-0.08966362, -0.04969037,  0.18250751]],

                    [[-0.16049379,  0.2600137 , -0.11920629],
                    [-0.28211683, -0.35937336, -0.2072631 ]]]], dtype=tf.float32),  # 自定义卷积核权重张量
     tf.constant([1, 2, 1.5], dtype=tf.float32)  # 自定义偏置张量
]
conv_layer.set_weights(weights_data)
print(conv_layer.weights)
y = conv_layer(x)
print(y)

[<tf.Variable 'kernel:0' shape=(3, 3, 2, 3) dtype=float32, numpy=
array([[[[ 0.17961133,  0.22007972, -0.2598019 ],
         [ 0.3186909 ,  0.24281353,  0.32523507]],

        [[ 0.11649853, -0.19694139, -0.3283413 ],
         [-0.10513568,  0.23352385,  0.13405755]],

        [[-0.12504146, -0.14563793,  0.35750693],
         [ 0.0198659 , -0.12209228,  0.17227197]]],


       [[[ 0.24108452, -0.3303193 ,  0.10114965],
         [-0.11957595, -0.3395833 , -0.03018716]],

        [[-0.20335948,  0.26378292, -0.2866226 ],
         [ 0.19164538,  0.32580817,  0.03058186]],

        [[ 0.36354887, -0.1988679 , -0.34951177],
         [-0.11006111,  0.19815278, -0.03410023]]],


       [[[ 0.30214107,  0.2538708 , -0.24634236],
         [ 0.33849055,  0.04826209, -0.04467008]],

        [[-0.03986514,  0.21542007, -0.15578839],
         [-0.08966362, -0.04969037,  0.18250751]],

        [[-0.16049379,  0.2600137 , -0.11920629],
         [-0.28211683, -0.35937336, -0.2072631 ]]]], dtype=float

In [ ]:

# conv_out = tf.constant([[
#                          [[1.1024821,  3.8124533,  0.7609668 ],
#                           [2.8853374,  2.4665523,  0.28976846]],

#                           [[3.612152,   2.4390607,  0.        ],
#                            [1.4035623,  3.6409013,  0.        ]]
#                          ]])
conv_out = tf.constant( [[
                          [[1, 2],
                          [1, 1],
                          [2, 1],
                          [1, 1]],

                          [[1, 1],
                          [4, 1],
                          [1, 3],
                          [1, 1]],

                          [[1, 1],
                          [1, 3],
                          [0, 1],
                          [1, 1]],

                          [[3, 1],
                          [1, 1],
                          [1, 1],
                          [1, 4]]
                      ]])
maxpool = tf.keras.layers.MaxPool2D(pool_size=(2, 2))
maxpool.build(conv_out.shape)
y = maxpool(conv_out)
print(y)


tf.Tensor(
[[[[4 2]
   [2 3]]

  [[3 3]
   [1 4]]]], shape=(1, 2, 2, 2), dtype=int32)


In [ ]:
maxpool_out = tf.constant( [[
                          [[1, 2],
                          [1, 1],
                          [2, 1],
                          [1, 1]],

                          [[1, 1],
                          [4, 1],
                          [1, 3],
                          [1, 1]],

                          [[1, 1],
                          [1, 3],
                          [0, 1],
                          [1, 1]],

                          [[3, 1],
                          [1, 1],
                          [1, 1],
                          [1, 4]]
                      ]])
flat = tf.keras.layers.Flatten()
flat.build(maxpool_out.shape)
y = flat(maxpool_out)
print(y)

tf.Tensor([[1 2 1 1 2 1 1 1 1 1 4 1 1 3 1 1 1 1 1 3 0 1 1 1 3 1 1 1 1 1 1 4]], shape=(1, 32), dtype=int32)


In [ ]:
flat = tf.constant([[1, 2, 1, 1, 2, 5, 3, 4]])
dense = tf.keras.layers.Dense(3, activation="softmax")
dense.build(flat.shape)

weights_data = [tf.constant([[ 0.8196276 , -0.26941723,  0.25858647],
                            [-0.01174253, -0.7430273 , -0.80889785],
                            [ 0.80310935,  0.03818017,  0.84339064],
                            [-0.44737333,  0.42151052, -0.4703352 ],
                            [ 0.16258484, -0.6799409 , -0.59610856],
                            [-0.29043275, -0.01559797, -0.17879911],
                            [ 0.16258484, -0.6799409 , -0.59610856],
                            [-0.29043275, -0.01559797, -0.17879911]], dtype=tf.float32),

              tf.constant([0., 0., 0.], dtype=tf.float32)
              ]
# weights_data = [
#     tf.constant([[ 0.20090851, -0.20784295, -0.34097043,  0.14663354,  0.20716736,
#          0.06907147, -0.30905133,  0.23814723, -0.18660611, -0.04469344],
#        [ 0.16411272,  0.27905306, -0.29043275, -0.01559797, -0.17879911,
#          0.11712536, -0.12421694, -0.3620003 ,  0.22993723,  0.0747754 ],
#        [-0.15889288, -0.23741017,  0.09809458, -0.17381807, -0.3060493 ,
#          0.00770977, -0.15302117, -0.07000828,  0.21064052, -0.24423827],
#        [ 0.16267261, -0.35420418, -0.09479851,  0.0789957 ,  0.28378937,
#          0.13730344,  0.07420543, -0.37563097,  0.25130168, -0.09308776],
#        [ 0.01811314, -0.33645907, -0.29486942, -0.1947332 , -0.35590598,
#         -0.00852594,  0.10780802, -0.1208638 ,  0.16006628,  0.34088853],
#        [-0.21732129, -0.04825899,  0.1718472 ,  0.14426479,  0.3714153 ,
#         -0.2281727 , -0.00321886,  0.31448093,  0.02589023,  0.02703673],
#        [-0.0659894 ,  0.01975465,  0.1680198 ,  0.3535652 , -0.17337705,
#         -0.09115204,  0.02223891, -0.06221607,  0.30953488,  0.32610628],
#        [-0.34968063,  0.09587318,  0.3030794 ,  0.11559594, -0.02733746,
#         -0.2012012 , -0.27842364,  0.10955292,  0.0514189 , -0.02412662],
#        [ 0.32919267,  0.31226936, -0.01461375, -0.05953869,  0.21524528,
#         -0.08135802,  0.02817371, -0.01535323, -0.02336669, -0.1740439 ],
#        [-0.19726017,  0.14667472, -0.10357457, -0.08002111,  0.1541312 ,
#          0.24982783,  0.2610344 ,  0.26762846,  0.3251997 , -0.07714638],
#        [-0.22798364, -0.33735904,  0.2394655 ,  0.34831002, -0.04190597,
#         -0.22294277,  0.24634776, -0.3380838 , -0.07132846,  0.01059422],
#        [ 0.1870611 , -0.3727558 , -0.17047404, -0.02016863, -0.2763685 ,
#         -0.3725058 , -0.2511226 ,  0.12136105,  0.1702458 ,  0.3157126 ],
#        [ 0.0041993 ,  0.26389274,  0.21866265, -0.160261  , -0.16267902,
#         -0.02289197,  0.08373612, -0.24552716, -0.13959071, -0.04884237],
#        [ 0.3200793 ,  0.30336913,  0.1130057 , -0.11708236,  0.18640932,
#          0.10560358,  0.27136114,  0.10402048, -0.20888746,  0.08710036],
#        [ 0.21462187, -0.34755883, -0.10778892,  0.07790226,  0.34215418,
#         -0.19160923,  0.24759564, -0.3411309 , -0.3684035 ,  0.31819734],
#        [ 0.06812483, -0.11391288,  0.13667086, -0.13756278, -0.3198364 ,
#         -0.08101487,  0.05973738,  0.14794669,  0.11703965,  0.16938964],
#        [-0.00543359,  0.08802843, -0.01606286,  0.09471101,  0.1734766 ,
#          0.25977567,  0.34441635,  0.06879646,  0.15784207, -0.23763375],
#        [-0.37448904,  0.06081191, -0.16115528, -0.16731754,  0.15565231,
#         -0.34783366,  0.24239984, -0.17092001,  0.14848414,  0.27133474],
#        [ 0.13050005,  0.24995574, -0.2059793 , -0.36968958,  0.21764472,
#         -0.20285939, -0.2197741 ,  0.00792405,  0.10027677, -0.03931186],
#        [ 0.303075  , -0.36209336, -0.05942082, -0.11736828,  0.12607715,
#          0.07829478,  0.2929487 ,  0.01533952, -0.03084099,  0.02604297],
#        [-0.25118208,  0.14710054,  0.03775603, -0.02442956, -0.27721387,
#          0.25665602,  0.0823746 ,  0.33378497, -0.35463887,  0.06757298],
#        [-0.05757087,  0.04856735,  0.31537405,  0.2655839 , -0.34283552,
#          0.28015998,  0.13006255, -0.32250547,  0.02273273,  0.26094213],
#        [-0.04547951,  0.26035348, -0.22656822,  0.3690243 , -0.20318398,
#          0.08086374,  0.26228985, -0.01881781, -0.25006565, -0.13173342],
#        [-0.00255573, -0.04554114, -0.29188618,  0.09734619, -0.08502883,
#         -0.08484119, -0.15518066,  0.25464192,  0.2142987 ,  0.27592775],
#        [ 0.0578151 ,  0.16421309,  0.16284373,  0.05849391,  0.31765094,
#         -0.18826385, -0.25415367,  0.0717757 , -0.16284762, -0.18812463],
#        [ 0.09007141, -0.34873924,  0.35180977, -0.02763996, -0.3291155 ,
#          0.07395068, -0.11763451,  0.22238633, -0.21463168,  0.07128718],
#        [ 0.33921745, -0.14996505,  0.02278644,  0.3636361 , -0.17109942,
#         -0.02408129, -0.12010857, -0.13787079, -0.35862705,  0.2077814 ],
#        [ 0.2545598 , -0.03870773, -0.04706892, -0.29356554,  0.1415048 ,
#         -0.3769944 ,  0.20443198,  0.21764109,  0.25294045,  0.07799003],
#        [ 0.2955568 , -0.23589464,  0.03251314,  0.31908026, -0.25254506,
#         -0.16418202,  0.35068962, -0.29650676,  0.2536787 ,  0.37507883],
#        [ 0.29401055, -0.23093668, -0.3462201 , -0.3407463 ,  0.2141976 ,
#          0.15590706, -0.02262369, -0.18910442,  0.00973427,  0.27618816],
#        [-0.28830597,  0.1523346 ,  0.09950343, -0.05100456, -0.2511319 ,
#         -0.27022797,  0.11442977, -0.20276603, -0.00233287,  0.0070141 ],
#        [-0.08905968, -0.21939653,  0.17184487,  0.26193866, -0.19118336,
#          0.19635072,  0.05889088,  0.36440757, -0.07381073, -0.04759493]], dtype=tf.float32),
#     tf.constant([0., 1., 0.1, 0., 0.2, 0., 0., 0.1, 0., 0.5],  dtype=tf.float32)
# ]

dense.set_weights(weights_data)
print(dense.weights)
y = dense(flat)
print(y)

[<tf.Variable 'kernel:0' shape=(8, 3) dtype=float32, numpy=
array([[ 0.8196276 , -0.26941723,  0.25858647],
       [-0.01174253, -0.7430273 , -0.80889785],
       [ 0.80310935,  0.03818017,  0.84339064],
       [-0.44737333,  0.42151052, -0.4703352 ],
       [ 0.16258484, -0.6799409 , -0.59610856],
       [-0.29043275, -0.01559797, -0.17879911],
       [ 0.16258484, -0.6799409 , -0.59610856],
       [-0.29043275, -0.01559797, -0.17879911]], dtype=float32)>, <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]
tf.Tensor([[0.9780477  0.01486163 0.00709054]], shape=(1, 3), dtype=float32)
