In [2]:
# Importing libraries
import numpy as np
import tensorflow as tf

In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
# Checking the version of tensorflow
print(tf.__version__)
# Are we running with Eager execution?
print(tf.executing_eagerly())

2.12.0
True


Output: tf.Tensor(
[[-0.9822196  -3.8741136  -3.61311     0.17016411 -2.3361073   0.43667626
   0.38660264 -1.78953    -1.9752529  -1.2235322 ]], shape=(1, 10), dtype=float32)


In [6]:
inputs = tf.random.normal(shape=(1, 10))
outputs = tf.keras.activations.softmax(inputs)
tf.reduce_sum(outputs[0, :])  # Each sample in the batch now sums to 1
outputs

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.03448792, 0.07957109, 0.0433877 , 0.08896935, 0.14871098,
        0.01463161, 0.08646329, 0.09538666, 0.38994756, 0.0184439 ]],
      dtype=float32)>